[workspace]
resolver = "2"
members = [
    "crates/octoscript-oh-arkui",
    "crates/octoscript-oh-core",
    "tools/octoscript-oh-cli",
    "crates/octoscript-oh-plugin-demo",
    "crates/octoscript-oh-webview",
    "examples/wechat",
    "examples/taobao",
    "examples/tiktok",
    "examples/wonderous",
    "examples/wonderous-makepad",
    "examples/material-catalog",
    "examples/flutter-catalog",
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
